### ISSUE TITLE
Issue with Stripe token

### ISSUE THREAD

**Issue by weisisheng** [mjzone/bookstore-v2#2]
I get to around the 45 minute mark in the video and everything is smooth.  However an error not mentioned surfaces related to token.

errorType: "Lambda:Unhandled"
locations: [{…}]
message: "SyntaxError: Invalid or unexpected token"
path: ["processOrder"]

Would appreciate any insights.  Otherwise awesome example!

ubuntu 20.04, aws-cli 1.18.102, aws-amplify 4.24.0, node 10.19.0

**Comment by mtliendo** [comment]
Hey @weisisheng 👋 

I see in your error message you have `
message: "SyntaxError: Invalid or unexpected token"`

Mind taking another look at your lambda to see if there are any syntax issues? Or feel free to post your lambda (sans any secrets) and I can take a deeper look

**Comment by weisisheng** [comment]
Thank you for the fast response.  I replaced the 2 lambdas and then had an issue with a missing uuid module in the createOrder function.  Added it and orders are successful.  Much appreciated.
